[package]
name = "ekubo_multiextension"
version = "0.1.0"
edition = "2024_07"

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
starknet = "2.9.2"

[dev-dependencies]
snforge_std = "0.35.1"
assert_macros = "2.9.2"

[[target.starknet-contract]]
sierra = true

[[tool.snforge.fork]]
name = "mainnet"
url = "https://free-rpc.nethermind.io/mainnet-juno"
block_id.number = "1088880"

[scripts]
test = "snforge test"

